---
title: "Highest Mountains on Earth"
author: "Patrick Meyer"
date: "4 2 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This map was created as part of the Developing Data Products Class on coursera.org. It incorporates a list of the highest mountains on earth as found on https://en.wikipedia.org/wiki/List_of_highest_mountains_on_Earth. 

Clicking on a marker will show you some information about the mountain as well as a link that redirects you to Wikipedia page of that mountain.


```{r evaluation, echo=FALSE, out.width = "100%", message=FALSE}
library(stringr)
library(leaflet)
library(tibble)

#Import data
dat = read.csv("HighestMountains.csv", sep = ";", na.strings = "NA")

#Add columns for coordinates and the text provided in the popup
dat = add_column(dat, lng = 1:119, .after = "Coordinates")
dat = add_column(dat, lat = 1:119, .after = "Coordinates")
dat = add_column(dat, Popup = "")

#Fill the new columns with by extracting the needed information from the messy coordinates column
for (i in 1:nrow(dat)) {
  dat$lat[i] = as.numeric(str_extract_all(string = dat$Coordinates[i], pattern = "[:digit:]+\\.[:digit:]+")[[1]][1])
  dat$lng[i] = as.numeric(str_extract_all(string = dat$Coordinates[i], pattern = "[:digit:]+\\.[:digit:]+")[[1]][2])
  dat$Popup[i] = paste("<a href='https://en.wikipedia.org/wiki/",
                        str_extract(string = dat$Mountain.name.s.[i], pattern = "[^,]+"), 
                        "'>", str_extract(string = dat$Mountain.name.s.[i], pattern = "[^,]+"), "</a>", 
                        "<br/>", "Height: ", dat$Height[i], "m / ", dat$Height.1[i], "ft", 
                        "<br/>", "long: ", dat$lng[i], ", lat: ", dat$lat[i], 
                        "<br/>", "First Ascent: ", dat$First.Ascents.before.2004[i],  
                        sep = ""
                      )
}

#remove the messy coordinates column
dat = dat[,-8]

#Draw a map with the data and add the markers including popups
dat %>%
  leaflet() %>%
  addTiles() %>%
  addMarkers(popup = dat$Popup)
```

